version: '2'
services:
  web:
    image: tigerxp/docker-majordomo:latest
    volumes:
      - ./docker-data/majordomo:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: majordomo
      DB_USER: root
      DB_PASS: example

  db:
    image: mariadb:latest
    volumes:
      - ./docker-data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: majordomo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    ports:
     - 8080:80
    volumes:
     - ./docker-data/pma:/sessions
