version: '2'
services:
  web:
    extends:
      file: compose-common.yml
      service: common
    depends_on:
      - db
      - cycles
    ports:
      - 80:80

  cycles:
    restart: always
    extends:
      file: compose-common.yml
      service: common
    depends_on:
      - db
    environment:
      S2G_BASE_URL: 'http://web:80'
    command: php cycle.php

  db:
    image: mariadb:latest
    volumes:
      - ./docker-data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: majordomo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    ports:
     - 8080:80
    volumes:
     - ./docker-data/pma:/sessions
